### PR TITLE
#5044: Add output tensors support for linear op

### PR DESCRIPTION
**Pull request by ruthreshx**
Started working on adding the support for Linear Op

### CODE REVIEW

**Comment by eyonland** [comment]
See the commit that I added.   I'm not following what is broken given that I removed the wrapper.

**Comment by ruthreshx** [comment]
> See the commit that I added. I'm not following what is broken given that I removed the wrapper.

Sure @eyonland , I will take a look.

**Review by eyonland — CHANGES_REQUESTED** [review]
We need a test that shows that shows that we do NOT pass in the output_tensors at all as a parameter, and a test where we do.

**Comment by razorback3** [comment]
Closing this PR according to https://github.com/tenstorrent-metal/tt-metal/issues/5044#issuecomment-2032963952

**Pull request closed without merging**
